---

- name: Pritunl Installation
  hosts: label_service_name_pritunl
  gather_facts: yes
  become: True
  roles:
    - {role: '../roles/pritunl', tags: 'pritunl'}
    - {role: '../roles/configs', tags: 'configs'}
